<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>zms9110750.Utils.Core</RootNamespace>
		<AssemblyName>zms9110750.Utils.Core</AssemblyName>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>