<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <RootNamespace>zms9110750.Utils.SingleExe</RootNamespace>

	  <Nullable>enable</Nullable>
	  <ImportProjectExtensionProps>true</ImportProjectExtensionProps>
	  <ImportProjectExtensionTargets>true</ImportProjectExtensionTargets>
	  <OutputType>Exe</OutputType>
	  
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SmallSharp" Version="2.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Utils.Core\Utils.Core.csproj" />
  </ItemGroup>

</Project>
