<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>zms9110750.Extensions.Utils</RootNamespace>
    <AssemblyName>zms9110750.Utils.Extensions</AssemblyName>
    <Nullable>enable</Nullable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);IS_LIB</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Update="TupleTaskGetAwaiter.tt">
      <LastGenOutput>TupleTaskGetAwaiter.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="TupleTaskGetAwaiter.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TupleTaskGetAwaiter.tt</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
</Project>
