<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>zms9110750.Utils.Canalot</RootNamespace>
		<AssemblyName>zms9110750.Utils.Canalot</AssemblyName>
		<Nullable>enable</Nullable>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Utils.UnionPolyfill\Utils.UnionPolyfill.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Extensions\Apply.tt">
			<Generator>TextTemplatingFileGenerator</Generator>
			<LastGenOutput>Apply.tt.cs</LastGenOutput>
		</None>
		<None Update="Extensions\Out.tt">
			<Generator>TextTemplatingFileGenerator</Generator>
			<LastGenOutput>Out.tt.cs</LastGenOutput>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Extensions\Apply.tt.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Apply.tt</DependentUpon>
		</Compile>
		<Compile Update="Extensions\Out.tt.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Out.tt</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
	  <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>

</Project>
