<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>zms9110750.Utils.Adapters.Demo</RootNamespace>
    <ImportProjectExtensionProps>true</ImportProjectExtensionProps>
    <ImportProjectExtensionTargets>true</ImportProjectExtensionTargets>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SmallSharp" Version="2.3.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="11.0.0" />
    <PackageReference Include="Autofac.Pooling" Version="*" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.0" />
    <PackageReference Include="ZiggyCreatures.FusionCache" Version="2.6.0" />
    <PackageReference Include="ZiggyCreatures.FusionCache.Serialization.SystemTextJson" Version="2.6.0" />
    <PackageReference Include="NeoSmart.Caching.Sqlite.AspNetCore" Version="9.*" />
    <PackageReference Include="Axion.Extensions.Polly.Caching.Hybrid" Version="10.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Utils.Adapters\Utils.Adapters.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Polly\Data\monsters.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
